# Generated by Django 5.2.7 on 2025-11-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Simpan nomor tanpa +, contohnya: 62812xxxx', max_length=20),
        ),
    ]
