# Generated by Django 5.2.7 on 2025-11-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0002_mahasiswa_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='alamat',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='pendidikan_terakhir',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
