# Generated by Django 5.2.7 on 2025-12-08 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0003_mahasiswa_alamat_mahasiswa_pendidikan_terakhir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='jurusan',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='tanggal_lahir',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='tempat_lahir',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='pendidikan_terakhir',
            field=models.CharField(blank=True, choices=[('SMA', 'SMA/SMK'), ('D3', 'D3'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('Lainnya', 'Lainnya')], max_length=20),
        ),
    ]
